### PR TITLE
UIREC-9 Transition to Receiving List

### PR DESCRIPTION
**Pull request by aliaksei-chumakou**
## Purpose
Make transition to Receiving Items page.
https://issues.folio.org/browse/UIREC-9

## Approach
It's a try to use separate route to Receiving List, so orders list and details shouldn't be triggered to load. Some code clean-up performed to reduce duplication.

## Learning
As a common practice there is using `?layer=` url param, but it triggers all component hierarchy lifecycle methods, so they fetch back-end info even if user isn't going to see it. In case of Receiving button it's a try to load only required component.

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [x] Duplication on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

### CODE REVIEW

**Comment by aliaksei-chumakou** [comment]
@craigmcnally Is it right usage of template? I'm still working on checkboxes to check the right ones, but in general?

**Comment by aliaksei-chumakou** [comment]
Merging this with commented out tests to unblock @AndreiShumski2 
I'll create a separate PR with proper tests

**Comment by craigmcnally** [comment]
I think you should at least check the "There are no breaking changes in this PR." as well.  Other than that I think that's the appropriate usage.  

Whether or not the boxes are checked is not the important thing here... what's important is that the person merging the PR thought about these things before clicking the merge button ;)  The boxes are a convenience, and a way to help quickly communicate the potential impact of this PR.

**Comment by craigmcnally** [comment]
@aliaksei-chumakou I think you should at least check the "There are no breaking changes in this PR." as well.  Other than that I think that's the appropriate usage.  

Whether or not the boxes are checked is not the important thing here... what's important is that the person merging the PR thought about these things before clicking the merge button ;)  The boxes are a convenience, and a way to help quickly communicate the potential impact of this PR.

**Pull request merged**
