### PR TITLE
UIOR-1313: fix parsing issue and remove the array brackets

### PR DESCRIPTION
**Pull request by alisher-epam**
## Purpose

[UIOR-1313](https://folio-org.atlassian.net/browse/UIOR-1313): fix parsing issue and remove the array brackets
The issue: 
BE is sending error message with params. The values of the params are in the string format `"[FA]"` and using `JSON.parse()` is failing since it is purely string not a json object
### Response
Screenshot 2024-09-27 at 16 57 19

### Fund code handler
Screenshot 2024-09-27 at 16 58 35

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by usavkov-epam** [comment]
Could you please describe the issue?

**Comment by alisher-epam** [comment]
> Could you please describe the issue?

Updated the PR description

**Review by SerhiiNosko — APPROVED** [review]

**Comment by alisher-epam** [comment]
@usavkov-epam

**Comment by usavkov-epam** [comment]
It seems strange to me. I think the response must contain a valid JSON string (for array in this case) instead of replacing brackets in regular expression. This field expected to be an array, so UI must handle it as an array of strings

**Review by SerhiiNosko — COMMENTED** [review]
I will check is it possible quickly to fix from BE side

**Comment by alisher-epam** [comment]
Closing the PR(duplicate task), In favour of the PR https://github.com/folio-org/ui-orders/pull/1653

**Pull request closed without merging**
