### PR TITLE
UIOR-153 remove yarn.lock

### PR DESCRIPTION
**Pull request by aliaksei-chumakou**
## Purpose
Remove alerts regarding legacy libs. also eslint folio config updated, and fixed 2 errors

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by craigmcnally** [comment]
Removing the yarn.lock so that github doesn't show alerts seems like we're hiding the problem, not solving it.

**Comment by aliaksei-chumakou** [comment]
@craigmcnally I'm not sure I've got your reason. We are not hiding this since github scans our package.json and there is no legacy or something. In case of yarn.lock there are some modules like stripes-testing, etc. containing third-party deps with obsolete versions. So basically, it's a question to these core packages to fix such alerts, am I wrong?

**Comment by aliaksei-chumakou** [comment]
@ttamj Hi Matt, do you have strong opinion if we need to use yarn.lock or not? Thanks

**Comment by craigmcnally** [comment]
> there are some modules like stripes-testing, etc. containing third-party deps with obsolete versions. 

I didn't realize this was the case.  I thought it was our deps that were outdated.

**Comment by craigmcnally** [comment]
Looks like most repos don't include a yarn.lock, though some like ui-eholdings do...  I'm fine with removing it given the clarification above.  @ttamj do please chime in though I'm curious what your opinion is on this.

**Comment by aliaksei-chumakou** [comment]
@craigmcnally Basically, Let's decide should we keep yarn.lock or not. It has not been added initially, and I've added it only today. After that if we keep it - we might ignore alerts and to notify repos responsible persons with legacy deps issues.

**Comment by ttamj** [comment]
This topic and comes up from time to time.  Maintaining a lock file is generally considered good practice as your module is less susceptible to outside variances that might break your build.  However, a ui-module's lock file is not considered when it comes time for deployment (a platform and it's lock file are responsible for that).  Either option works, but if you choose to keep your lock file, you will also need to maintain it.

**Comment by craigmcnally** [comment]
@aliaksei-chumakou let's just remove it.  Thanks

**Pull request merged**
