### PR TITLE
FOLIO-1818 * TEST Do not merge * Sonar new code coverage

### PR DESCRIPTION
**Pull request by dcrossleyau**

### CODE REVIEW

**Comment by dcrossleyau** [comment]
@aliaksei-chumakou Would you please add a sensible portion of new code to test this. And remove my useless change.
(This PR will not be merged.)

**Comment by aliaksei-chumakou** [comment]
@dcrossleyau I've added new function and a test for it, but test coverage haven't been changed

**Comment by dcrossleyau** [comment]
Okay, thanks i will explore further.

**Comment by dcrossleyau** [comment]
Closing this PR. Need new one because the jenkins-pipeline-libs branch is updated.

**Pull request closed without merging**
